name: commitlint
description: Lint commit messages with GitHub Actions.
author: remarkablemark

inputs:
  config:
    description: Config to enforce conventional commits
    default: '@commitlint/config-conventional'

  from:
    description: Lower end of the commit range to lint
    default: HEAD~1

  version:
    description: Version of @commitlint/cli
    default: latest

runs:
  using: composite
  steps:
    - name: Install commitlint
      shell: bash
      run: |
        command -v commitlint || npm install --silent --global commitlint@${{ inputs.version }}
        commitlint --version

    - name: Check config
      shell: bash
      run: |
        CONFIG=$(commitlint --print-config --no-color)

        RULES_LENGTH=$(node <<EOF
          const config = $CONFIG;
          console.log(Object.keys(config.rules).length);
        EOF)

        if [[ $RULES_LENGTH == 0 ]]; then
          npm install --silent --global ${{ inputs.config }}
          echo '{"extends":["${{ inputs.config }}"]}' > .commitlintrc.json
        fi

    - name: Run commitlint
      shell: bash
      run: commitlint --from=${{ inputs.from }}

    - name: Cleanup
      shell: bash
      run: |
        npm uninstall --silent --global commitlint @commitlint/config-conventional
        git reset --hard && git clean -d --force

branding:
  icon: terminal
  color: gray-dark
