name: lintcommit
description: Lint commit messages with GitHub Actions.
author: remarkablemark

inputs:
  checkout:
    description: Whether to checkout the repository
    required: false
    default: false

  config:
    description: Config to enforce conventional commits
    required: false
    default: '@commitlint/config-conventional'

  from:
    description: Lower end of the commit range to lint
    required: false
    default: HEAD~1

  version:
    description: Version of @commitlint/cli
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: inputs.checkout == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install commitlint
      shell: bash
      run: |
        npm install --silent --global commitlint@${{ toJSON(inputs.version) }}

        if [[ '${{ runner.debug }}' == 1 ]]; then
          commitlint --version
        fi

    - name: Get config
      shell: bash
      run: |
        if [[ -f package.json ]] && grep --quiet '"@commitlint/' package.json; then
          npm install --silent
          exit 0
        fi

        CONFIG=$(commitlint --print-config --no-color)

        RULES_LENGTH=$(node <<EOF
          const config = $CONFIG;
          console.log(Object.keys(config.rules).length);
        EOF
        )

        if [[ $RULES_LENGTH == 0 ]]; then
          npm install --silent --no-save ${{ toJSON(inputs.config) }}
          cat <<'EOF' > .commitlintrc.json
          {
            "extends": [${{ toJSON(inputs.config) }}],
            "rules": {
              "body-max-line-length": [1, "always", 100],
              "footer-max-line-length": [1, "always", 100]
            }
          }
        EOF
        fi

    - name: Run commitlint
      shell: bash
      run: commitlint --from=${{ toJSON(inputs.from) }}

    - name: Cleanup
      shell: bash
      run: |
        npm uninstall --silent --global commitlint
        git reset --hard 1> /dev/null
        git clean -d --force 1> /dev/null

branding:
  icon: terminal
  color: gray-dark
